vertical_coverage_per_row: 2
horizontal_span_per_col:   1
mirror_bonus:              1

baseline_straight_bonus:   2
baseline_boxed_bonus:      1

straight_2rows_bonus:      1
straight_3rows_bonus:      3

extra_digit_per_char:      1

single_left_bonus:         4

consensus_full_bonus:      4
stub_consensus_score:      4

hot_level_1_bonus:         1
hot_level_2_bonus:         2

min_score_to_highlight:    8

dominant_last_bonus:   2
dominant_pair_bonus:   1
dominant_double3_bonus: 1
